name: Build and Deploy Quarto

on:
  schedule:
    - cron: "0 3 2,17 * *" # todo dia 2 e 17 às 3:00 UTC (00:00 no Brasil)
  workflow_dispatch: # permite executar manualmente
  push:
    branches:
      - view1-rembase

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libpng-dev \
          libfreetype6-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libfontconfig1-dev \
          libtiff5-dev \
          libjpeg-dev \
          libxml2-dev \
          libcurl4-openssl-dev \
          libssl-dev \
          libgit2-dev

      - name: Instalar pacotes R necessários
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            RPostgres
            DBI
            dotenv
            quarto
            tidyverse
            here
            zoo
            patchwork
            colorspace
            showtext
            hrbrthemes
            ggtext

      - name: Realizar extração do banco
        run: |
          GITHUB_ACTIONS=true Rscript tasks/view-remuneracao-base/src/01-extracao.R
          GITHUB_ACTIONS=true Rscript tasks/view-outras-remuneracoes/src/01-extracao.R
        env:
          DADOSJUSBR_DBNAME: ${{ secrets.DADOSJUSBR_DBNAME }}
          DADOSJUSBR_DBUSER: ${{ secrets.DADOSJUSBR_DBUSER }}
          DADOSJUSBR_DBSECRET: ${{ secrets.DADOSJUSBR_DBSECRET }}
          DADOSJUSBR_DBHOST: ${{ secrets.DADOSJUSBR_DBHOST }}

      - name: Renderizar HTML com Quarto
        run: |
          quarto render tasks/view-remuneracao-base/src/02-remuneracao-base.qmd
          quarto render tasks/view-outras-remuneracoes/src/03-outras-remuneracoes.qmd

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: view1-rembase
